[package]
name = "rs-NaneExchanger"
version = "1.0.0"
edition = "2021"

[lib]
name = "exchange_lib"
path = "lib/lib.rs"

[[bin]]
name = "NaneExchanger"
path = "src/main.rs"

[build-dependencies]
winres = "0.1.12"

[dependencies]
eframe = "0.31.1"
tray-icon = "0.20.0"
windows-sys = "0.59.0"
winit = "0.30.9"
mslnk = "0.1.8"

[profile.release]
lto = true
opt-level = "z"
strip = true
