[package]
name = "rs-NaneExchanger"
version = "1.0.0"
edition = "2021"

[lib]
name = "exchange_lib"
path = "lib/lib.rs"

[[bin]]
name = "NameExchanger"
path = "src/main.rs"

[build-dependencies]
winres = "0.1.12"

[dependencies]
directories = "6.0.0"
native-windows-gui = "1.0.12"
native-windows-derive = "1.0.3"
tray-item = "0.10.0"
mslnk = "0.1.8"

[profile.release]
lto = true
opt-level = "z"
strip = true
