import "./NameExchangeCustom.ttf";

import {
    LineEdit,
    Button,
    StandardButton,
    TextEdit,
    ScrollView,
} from "std-widgets.slint";

component TitleBar inherits Rectangle {
    width: 400px;
    height: 40px;
    background: #0070cb;
    x: 0;
    y: 0;

    in-out property <bool> is_top: true;

    area_pin := TouchArea {
        x: 0px;
        width: 40px;
        height: 40px;
        clicked => {
            root.is_top = !root.is_top;
        }
        Text {
            width: 40px;
            height: 40px;
            x: 0px;
            text: root.is_top ? "B" : "A";
            font-family: "NameExchangeCustom";
            font-size: 16pt;
            vertical-alignment: center;
            horizontal-alignment: center;
            color: #ffff00;
        }
    }

    callback help_clicked();
    area_help := TouchArea {
        x: 192px;
        width: 40px;
        height: 40px;
        clicked => {
            root.help_clicked();
        }
        Text {
            x: 0px;
            width: 40px;
            height: 40px;
            text: "C";
            font-family: "NameExchangeCustom";
            font-size: 16pt;
            vertical-alignment: center;
            horizontal-alignment: center;
            color: #ff0000;
        }
    }

    in-out property <bool> is_admin;
    callback admin_clicked();
    area_admin := TouchArea {
        x: 234px;
        width: 40px;
        height: 40px;
        clicked => {
            root.admin_clicked();
            is_admin = !is_admin;
        }
        Text {
            font-family: "NameExchangeCustom";
            width: 40px;
            height: 40px;
            text: root.is_admin ? "E" : "D";
            x: 0px;
            font-size: 16pt;
            vertical-alignment: center;
            horizontal-alignment: center;
            color: #ffffff;
        }
    }

    area_link := TouchArea {
        x: 276px;
        width: 40px;
        height: 40px;
        clicked => {
        //link
        }
        Text {
            font-family: "NameExchangeCustom";
            width: 40px;
            height: 40px;
            text: "F";
            x: 0;
            font-size: 16pt;
            vertical-alignment: center;
            horizontal-alignment: center;
            color: #ffffff;
        }
    }

    area_min := TouchArea {
        x: 318px;
        width: 40px;
        height: 40px;
        clicked => {
            //min
        }
        Text {
            font-family: "NameExchangeCustom";
            width: 40px;
            height: 40px;
            text: "G";
            x: 0;
            font-size: 16pt;
            vertical-alignment: center;
            horizontal-alignment: center;
            color: #ffffff;
        }
    }

    area_close := TouchArea {
        x: 360px;
        width: 40px;
        height: 40px;
        clicked => {
            //close
        }
        Text {
            font-family: "NameExchangeCustom";
            width: 40px;
            height: 40px;
            text: "H";
            x: 0;
            font-size: 16pt;
            vertical-alignment: center;
            horizontal-alignment: center;
            color: #ffffff;
        }
    }
}

export component MainWindow inherits Window {
    width: 400px;
    height: 280px;
    always-on-top: true;
    in-out property <bool> is_admin: false;
    in-out property <string> msgbox_message: "";
    callback request_help();
    callback admin_switch();

    TitleBar {
        is_top <=> root.always-on-top;
        is_admin: root.is_admin;
        help_clicked => {
            root.request_help();
            help_dialog.show();
        }
        admin_clicked => {
            root.admin_switch()
        }
    }

    help_dialog := PopupWindow {
        close-policy: no-auto-close;
        width: 320px;
        height: 240px;
        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;

        VerticalLayout {
            padding: 16px;
            spacing: 12px;

            Text {
                text: "帮助";
                font-size: 16px;
                font-weight: 700;
            }

            ScrollView {
                height: 140px;
                Text {
                    text: root.msgbox_message;
                    //hard to scroll
                    wrap: word-wrap;
                }
            }

            HorizontalLayout {
                alignment: center;
                Button {
                    text: "OK";
                    clicked => {
                        help_dialog.close();
                    }
                }
            }
        }
    }
}
