import "./NameExchangeCustom.ttf";

import {
    LineEdit,
    Button,
    StandardButton,
    TextEdit,
    ScrollView,
} from "std-widgets.slint";

component TitleBar inherits Rectangle {
    width: 400px;
    height: 40px;
    background: #0070cb;
    x: 0;
    y: 0;

    in-out property <bool> is_top: true;

    area_pin := TouchArea {
        x: 0px;
        width: 40px;
        height: 40px;
        clicked => {
            root.is_top = !root.is_top;
        }
        Text {
            width: 40px;
            height: 40px;
            x: 0px;
            text: root.is_top ? "B" : "A";
            font-family: "NameExchangeCustom";
            font-size: 16pt;
            vertical-alignment: center;
            horizontal-alignment: center;
            color: #ffff00;
        }
    }

    callback help_clicked();
    area_help := TouchArea {
        x: 192px;
        width: 40px;
        height: 40px;
        clicked => {
            root.help_clicked();
        }
        Text {
            x: 0px;
            width: 40px;
            height: 40px;
            text: "C";
            font-family: "NameExchangeCustom";
            font-size: 16pt;
            vertical-alignment: center;
            horizontal-alignment: center;
            color: #ff0000;
        }
    }

    in-out property <bool> is_admin;
    callback admin_clicked();
    area_admin := TouchArea {
        x: 234px;
        width: 40px;
        height: 40px;
        clicked => {
            root.admin_clicked();
            is_admin = !is_admin;
        }
        Text {
            font-family: "NameExchangeCustom";
            width: 40px;
            height: 40px;
            text: root.is_admin ? "E" : "D";
            x: 0px;
            font-size: 16pt;
            vertical-alignment: center;
            horizontal-alignment: center;
            color: #ffffff;
        }
    }

    Text {
        font-family: "NameExchangeCustom";
        width: 40px;
        height: 40px;
        text: "F";
        x: 276px;
        font-size: 16pt;
        vertical-alignment: center;
        horizontal-alignment: center;
        color: #ffffff;
    }

    Text {
        font-family: "NameExchangeCustom";
        width: 40px;
        height: 40px;
        text: "G";
        x: 318px;
        font-size: 16pt;
        vertical-alignment: center;
        horizontal-alignment: center;
        color: #ffffff;
    }

    Text {
        font-family: "NameExchangeCustom";
        width: 40px;
        height: 40px;
        text: "H";
        x: 360px;
        font-size: 16pt;
        vertical-alignment: center;
        horizontal-alignment: center;
        color: #ffffff;
    }
}

export component HelpInfo inherits Dialog {
    in-out property <bool> help_show;
    Text {
        wrap: word-wrap;
        text: "拖入文件即可使用，软件将常驻任务栏，悬停鼠标于\n按钮上可获得提示。\n\n软件包含以下功能\n〇管理员身份启动\n〇创建/删除「发送到」菜单快捷方式\n〇置顶\n\n拖入檔案即可使用，軟體將常駐系統匣，懸停鼠標於\n按鈕上可獲得提示。\n\n軟體包含以下功能\n〇總是以系統管理員執行\n〇建立/刪除「傳送到」選單捷徑方式\n〇置頂";
    }

    StandardButton {
        kind: ok;
    }
}

export component MainWindow inherits Window {
    width: 400px;
    height: 280px;
    always-on-top: true;
    in-out property <bool> is_admin: false;
    in-out property <string> msgbox_message: "";
    in-out property <bool> help_show: false;
    callback request_help();
    callback admin_switch();
    TitleBar {
        is_top <=> root.always-on-top;
        is_admin: root.is_admin;
        help_clicked => {
            help_show = true;
        }
        admin_clicked => {
            root.admin_switch()
        }
    }
}
